/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class HelloWorld {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new HelloWorld().getGreeting());
    }
}
